spring:
  application:
    name: confirmation
  cloud:
    stream:
      bindings:
        payments:
          group: 'confirmation'
          consumer:
            prefetch: 100
management:
  metrics:
    export:
      wavefront:
        source: confirmation
wavefront:
  application:
    name: tanzu-demo