management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      wavefront:
        source: b2b-accounts
server:
  port: 8081
spring:
  application:
    name: b2b-accounts
  cloud:
    stream:
      bindings:
        confirmations:
          group: accounts
  zipkin:
    discovery-client-enabled: false
    service:
      name: b2b-accounts
    sender:
      type: web