apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: b2b-accounts
  namespace: kpack
spec:
  tag: dhubau/b2b-accounts
  serviceAccount: kpack-service-account
  builder:
    name: custom-java-builder
    kind: CustomBuilder
  cacheSize: "2Gi"
  source:
    git:
      url: https://github.com/Turbots/b2b.git
      revision: master
    subPath: "b2b-accounts"