apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: account-service
spec:
  destination:
    server: 'DEV_CLUSTER_URL'
    namespace: WORKLOAD_NAMESPACE
  source:
    path: 'account-service'
    repoURL: 'https://github.com/Turbots/tanzu-demo-gitops'
    targetRevision: master
  project: default
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
      prune: true
      selfHeal: true
