apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: redis-ENVIRONMENT
spec:
  destination:
    server: 'CLUSTER_URL'
    namespace: WORKLOAD_NAMESPACE
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 10.6.13
    chart: redis
    helm:
      parameters:
      - name: existingSecret
        value: 'redis'
      - name: existingSecretPasswordKey
        value: 'redis-password'
  project: ENVIRONMENT
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
      prune: true
      selfHeal: true