spring:
  application:
    name: b2b-confirmation
  cloud:
    stream:
      bindings:
        payments:
          group: 'b2b-confirmation'
          consumer:
            prefetch: 100
  zipkin:
    service:
      name: Confirmation