concourse:
    web:
        externalUrl: http://concourse.beijing.cf-app.com # CONCOURSE PUBLIC URL - ADD DNS RECORD FOR THIS
        bindPort: 80
        localAuth:
            enabled: true
        kubernetes:
            enabled: true
web:
    service:
        type: LoadBalancer