---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b2b-confirmation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: b2b-confirmation
  template:
    metadata:
      labels:
        app: b2b-confirmation
    spec:
      containers:
        - name: b2b-confirmation
          image: docker.io/dhubau/b2b-confirmation:latest
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_USERNAME
              value: user
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
            - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
              value: 'proxy://wavefront-proxy:2878'
            - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: wavefront
                  key: token
          resources:
            requests:
              memory: 1024Mi
              cpu: 500m
            limits:
              memory: 1024Mi
          ports:
            - containerPort: 8080