---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b2b-payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: b2b-payments
  template:
    metadata:
      labels:
        app: b2b-payments
    spec:
      containers:
        - name: b2b-payments
          image: docker.io/dhubau/b2b-payments:latest
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_USERNAME
              value: user
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
          resources:
            requests:
              memory: 1024Mi
              cpu: 500m
            limits:
              memory: 1024Mi
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: b2b-payments
  labels:
    app: b2b-payments
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: b2b-payments