spring:
  application:
    name: b2b-payments
  data:
    jpa:
      repositories:
        bootstrap-mode: LAZY
  jpa:
    hibernate:
      ddl-auto: validate
      id:
        new_generator_mappings: false
  flyway:
    baseline-on-migrate: true
  datasource:
    hikari:
      jdbc-url: 'jdbc:h2:mem:paymentdb'
  zipkin:
    service:
      name: Payments