spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: LAZY
  jpa:
    hibernate:
      ddl-auto: validate
      id:
        new_generator_mappings: false
    properties:
      hibernate:
        generate_statistics: true
  flyway:
    baseline-on-migrate: true
  datasource:
    hikari:
      jdbc-url: 'jdbc:h2:mem:paymentdb'
opentracing:
  jaeger:
    http-sender:
      url: 'http://wavefront-proxy:14267/api/traces'